# Generated by Django 3.1.2 on 2020-10-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201020_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='board',
        ),
        migrations.AddField(
            model_name='board',
            name='player',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='channel_name',
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
