# Generated by Django 3.1.2 on 2020-10-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20201027_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_ready',
        ),
    ]
