# Generated by Django 3.1.2 on 2020-10-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_player_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to='game.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='playerA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerA', to='game.player'),
        ),
    ]
